{% set name = "pychromatic" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pychromatic-{{ version }}.tar.gz
  sha256: 8a2cfaa8485bdc0051eaa97a8d91050bd110bb438616f6ffd667c490c771d182

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
    - setuptools
  run:
    - cycler
    - numpy
    - python >={{ python_min }}
    - matplotlib-base
    - rich

test:
  imports:
    - pychromatic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/srmnitc/pychromatic
  summary: a pretty color selector for python
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
