{% set name = "pychromatic" %}
{% set version = "0.5.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pychromatic-{{ version }}.tar.gz
  sha256: 77ab018f82aa0c88e25c4a23174cb35764416997cbe98b9d16eebdbe16cd9c86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - rich

test:
  imports:
    - pychromatic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/srmnitc/pychromatic
  summary: a pretty color selector for python
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
